## Arrays

In [1]:
import numpy as np

In [2]:
mysquare = np.array( [ [ 0,1,2 ],[ 3,4,5 ],[ 6,7,8 ] ] )
mysquare

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
mysquare[0]

array([0, 1, 2])

## Data Type

In [4]:
mysquare.dtype

dtype('int64')

## Arrays Computation

In [5]:
r = [ 2,2 ]
x = r * 2
x

[2, 2, 2, 2]

In [6]:
r = [ 2,2 ]
s = np.array( r )
x = s * 2
x

array([4, 4])

In [7]:
r = [ 2,2 ]
s = np.array( r )
x = np.array( [ 3 ] * 2 ) + s
x

array([5, 5])

## Array Data

In [8]:
data = np.loadtxt( 'inflammation.csv',delimiter=',' )
print( data.shape )

(60, 40)


In [9]:
myarray = np.array( [ 0,1,2,3,4,5,6,7,8,9,10 ] )
myarray_squared = myarray ** 2
myarray_squared

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## Data Access

In [10]:
mysquare

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
mysquare[ 1,2 ]

5

In [12]:
mysquare[ 1 ][ 2 ]

5

In [13]:
mysquare[ :,1 ]

array([1, 4, 7])

In [14]:
mysquare[ 1,: ]

array([3, 4, 5])

In [15]:
mysquare[ 0:2,0:2 ]

array([[0, 1],
       [3, 4]])

In [16]:
corner = mysquare[ 0:2,0:2 ]
corner

array([[0, 1],
       [3, 4]])

In [17]:
corner[ 0,0 ] = 100
mysquare

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

## Convenience Functions

In [18]:
np.zeros( ( 3,3 ) )

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones( ( 4,4 ) )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.eye( 4 )

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Matrix

### transpose

In [21]:
mysquare=mysquare.T #transpose
mysquare

array([[100,   3,   6],
       [  1,   4,   7],
       [  2,   5,   8]])

In [22]:
mysquare.tolist()

[[100, 3, 6], [1, 4, 7], [2, 5, 8]]

In [23]:
mysquare

array([[100,   3,   6],
       [  1,   4,   7],
       [  2,   5,   8]])

### Sort

In [24]:
mysquare[0,0]=100
mysquare.sort()
mysquare

array([[  3,   6, 100],
       [  1,   4,   7],
       [  2,   5,   8]])

### Multiplication

In [25]:
mysquare * mysquare# multiply elementwise (not as matrix)

array([[    9,    36, 10000],
       [    1,    16,    49],
       [    4,    25,    64]])

In [26]:
mysquare.dot( mysquare )# multiply as matrix

array([[ 215,  542, 1142],
       [  21,   57,  184],
       [  27,   72,  299]])

### linspace,arrange

'linspace' is a particularly useful method for scientific simulation:

In [27]:
xs = np.linspace( 0,10,101 )
ys = xs ** 2

'arange' should be avoided due to numerical error (truncation).

In [28]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

## Vector Operations

In [29]:
np.sin( myarray )

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [30]:
np.tanh( myarray )

array([0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ,
       0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997,
       1.        ])

In [31]:
np.exp( -myarray )

array([1.00000000e+00, 3.67879441e-01, 1.35335283e-01, 4.97870684e-02,
       1.83156389e-02, 6.73794700e-03, 2.47875218e-03, 9.11881966e-04,
       3.35462628e-04, 1.23409804e-04, 4.53999298e-05])